"""initial schema

Revision ID: c9428fb30df7
Revises: 
Create Date: 2026-08-21 16:04:08.185431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9428fb30df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_otps_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('primary_index', sa.String(length=20), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_label', sa.String(length=30), nullable=True),
    sa.Column('calibrated', sa.Boolean(), nullable=True),
    sa.Column('risk_high', sa.Float(), nullable=True),
    sa.Column('risk_medium', sa.Float(), nullable=True),
    sa.Column('risk_low', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('fov_deg', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.String(length=60), nullable=True),
    sa.Column('condition_name', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(length=20), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('battery_percent', sa.Integer(), nullable=True),
    sa.Column('tank_percent', sa.Integer(), nullable=True),
    sa.Column('gps_satellites', sa.Integer(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('total_flights', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('speed_ms', sa.Float(), nullable=True),
    sa.Column('overlap_pct', sa.Integer(), nullable=True),
    sa.Column('line_spacing_m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('waypoint_count', sa.Integer(), nullable=True),
    sa.Column('waypoints', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('identifier', sa.String(length=160), nullable=True),
    sa.Column('issuer', sa.String(length=120), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spray_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=60), nullable=True),
    sa.Column('shot_id', sa.String(length=60), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('index_key', sa.String(length=20), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('severe_fraction', sa.Float(), nullable=True),
    sa.Column('moderate_fraction', sa.Float(), nullable=True),
    sa.Column('healthy_fraction', sa.Float(), nullable=True),
    sa.Column('patch_count', sa.Integer(), nullable=True),
    sa.Column('field_ha', sa.Float(), nullable=True),
    sa.Column('chosen_option', sa.String(length=30), nullable=True),
    sa.Column('treated_fraction', sa.Float(), nullable=True),
    sa.Column('saving_percent', sa.Integer(), nullable=True),
    sa.Column('chemical_l', sa.Float(), nullable=True),
    sa.Column('saved_l', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('map_path', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spray_prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spray_prescriptions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spray_prescriptions_shot_id'), ['shot_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_updates', sa.Boolean(), nullable=False),
    sa.Column('ai_alerts', sa.Boolean(), nullable=False),
    sa.Column('field_reports', sa.Boolean(), nullable=False),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organisation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('index_key', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capture_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=60), nullable=False),
    sa.Column('shot_id', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('preview_path', sa.String(length=300), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt_m', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_frames_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_frames_shot_id'), ['shot_id'], unique=False)

    op.create_table('field_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=60), nullable=True),
    sa.Column('shot_id', sa.String(length=60), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=30), nullable=True),
    sa.Column('condition_id', sa.String(length=60), nullable=True),
    sa.Column('condition_name', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(length=20), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('weed_coverage', sa.Float(), nullable=True),
    sa.Column('weed_pressure', sa.String(length=20), nullable=True),
    sa.Column('weed_method', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('overlay_path', sa.String(length=300), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['capture_frames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_scans_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_scans_shot_id'), ['shot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_scans_shot_id'))
        batch_op.drop_index(batch_op.f('ix_field_scans_session_id'))

    op.drop_table('field_scans')
    with op.batch_alter_table('capture_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_frames_shot_id'))
        batch_op.drop_index(batch_op.f('ix_capture_frames_session_id'))

    op.drop_table('capture_frames')
    op.drop_table('alert_records')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    with op.batch_alter_table('spray_prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spray_prescriptions_shot_id'))
        batch_op.drop_index(batch_op.f('ix_spray_prescriptions_session_id'))

    op.drop_table('spray_prescriptions')
    op.drop_table('pilot_credentials')
    op.drop_table('missions')
    op.drop_table('drones')
    op.drop_table('disease_scans')
    op.drop_table('camera_feeds')
    op.drop_table('analysis_records')
    op.drop_table('users')
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_otps_email'))

    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
